package unicode;
// Kugel's "Java Code & Tools Library", Copyright (c) 1999-2007, Theossos Comp Group

/**
 * Unicode Arabic Supplement block with characters from u0750 to u077F.
 * @author Kugel, <i>Theossos Comp Group</i>
 * @version Unicode 4.1.0
 */
public interface ArabicSupplement
{
   // constant field names modified with "^ARABIC " pattern 
   char LETTER_BEH_WITH_THREE_DOTS_HORIZONTALLY_BELOW = '\u0750';
   char LETTER_BEH_WITH_DOT_BELOW_AND_THREE_DOTS_ABOVE = '\u0751';
   char LETTER_BEH_WITH_THREE_DOTS_POINTING_UPWARDS_BELOW = '\u0752';
   char LETTER_BEH_WITH_THREE_DOTS_POINTING_UPWARDS_BELOW_AND_TWO_DOTS_ABOVE = '\u0753';
   char LETTER_BEH_WITH_TWO_DOTS_BELOW_AND_DOT_ABOVE = '\u0754';
   char LETTER_BEH_WITH_INVERTED_SMALL_V_BELOW = '\u0755';
   char LETTER_BEH_WITH_SMALL_V = '\u0756';
   char LETTER_HAH_WITH_TWO_DOTS_ABOVE = '\u0757';
   char LETTER_HAH_WITH_THREE_DOTS_POINTING_UPWARDS_BELOW = '\u0758';
   char LETTER_DAL_WITH_TWO_DOTS_VERTICALLY_BELOW_AND_SMALL_TAH = '\u0759';
   char LETTER_DAL_WITH_INVERTED_SMALL_V_BELOW = '\u075A';
   char LETTER_REH_WITH_STROKE = '\u075B';
   char LETTER_SEEN_WITH_FOUR_DOTS_ABOVE = '\u075C';
   char LETTER_AIN_WITH_TWO_DOTS_ABOVE = '\u075D';
   char LETTER_AIN_WITH_THREE_DOTS_POINTING_DOWNWARDS_ABOVE = '\u075E';
   char LETTER_AIN_WITH_TWO_DOTS_VERTICALLY_ABOVE = '\u075F';
   char LETTER_FEH_WITH_TWO_DOTS_BELOW = '\u0760';
   char LETTER_FEH_WITH_THREE_DOTS_POINTING_UPWARDS_BELOW = '\u0761';
   char LETTER_KEHEH_WITH_DOT_ABOVE = '\u0762';
   char LETTER_KEHEH_WITH_THREE_DOTS_ABOVE = '\u0763';
   char LETTER_KEHEH_WITH_THREE_DOTS_POINTING_UPWARDS_BELOW = '\u0764';
   char LETTER_MEEM_WITH_DOT_ABOVE = '\u0765';
   char LETTER_MEEM_WITH_DOT_BELOW = '\u0766';
   char LETTER_NOON_WITH_TWO_DOTS_BELOW = '\u0767';
   char LETTER_NOON_WITH_SMALL_TAH = '\u0768';
   char LETTER_NOON_WITH_SMALL_V = '\u0769';
   char LETTER_LAM_WITH_BAR = '\u076A';
   char LETTER_REH_WITH_TWO_DOTS_VERTICALLY_ABOVE = '\u076B';
   char LETTER_REH_WITH_HAMZA_ABOVE = '\u076C';
   char LETTER_SEEN_WITH_TWO_DOTS_VERTICALLY_ABOVE = '\u076D';
}
