package unicode;
// Kugel's "Java Code & Tools Library", Copyright (c) 1999-2007, Theossos Comp Group

/**
 * Unicode CJK Compatibility Forms block with characters from uFE30 to uFE4F.
 * @author Kugel, <i>Theossos Comp Group</i>
 * @version Unicode 4.1.0
 */
public interface CjkCompatibilityForms
{
   char GLYPH_FOR_VERTICAL_TWO_DOT_LEADER = '\uFE30';
   char GLYPH_FOR_VERTICAL_EM_DASH = '\uFE31';
   char GLYPH_FOR_VERTICAL_EN_DASH = '\uFE32';
   char GLYPH_FOR_VERTICAL_SPACING_UNDERSCORE = '\uFE33';
   char GLYPH_FOR_VERTICAL_SPACING_WAVY_UNDERSCORE = '\uFE34';
   char GLYPH_FOR_VERTICAL_OPENING_PARENTHESIS = '\uFE35';
   char GLYPH_FOR_VERTICAL_CLOSING_PARENTHESIS = '\uFE36';
   char GLYPH_FOR_VERTICAL_OPENING_CURLY_BRACKET = '\uFE37';
   char GLYPH_FOR_VERTICAL_CLOSING_CURLY_BRACKET = '\uFE38';
   char GLYPH_FOR_VERTICAL_OPENING_TORTOISE_SHELL_BRACKET = '\uFE39';
   char GLYPH_FOR_VERTICAL_CLOSING_TORTOISE_SHELL_BRACKET = '\uFE3A';
   char GLYPH_FOR_VERTICAL_OPENING_BLACK_LENTICULAR_BRACKET = '\uFE3B';
   char GLYPH_FOR_VERTICAL_CLOSING_BLACK_LENTICULAR_BRACKET = '\uFE3C';
   char GLYPH_FOR_VERTICAL_OPENING_DOUBLE_ANGLE_BRACKET = '\uFE3D';
   char GLYPH_FOR_VERTICAL_CLOSING_DOUBLE_ANGLE_BRACKET = '\uFE3E';
   char GLYPH_FOR_VERTICAL_OPENING_ANGLE_BRACKET = '\uFE3F';
   char GLYPH_FOR_VERTICAL_CLOSING_ANGLE_BRACKET = '\uFE40';
   char GLYPH_FOR_VERTICAL_OPENING_CORNER_BRACKET = '\uFE41';
   char GLYPH_FOR_VERTICAL_CLOSING_CORNER_BRACKET = '\uFE42';
   char GLYPH_FOR_VERTICAL_OPENING_WHITE_CORNER_BRACKET = '\uFE43';
   char GLYPH_FOR_VERTICAL_CLOSING_WHITE_CORNER_BRACKET = '\uFE44';
   char SESAME_DOT = '\uFE45';
   char WHITE_SESAME_DOT = '\uFE46';
   char PRESENTATION_FORM_FOR_VERTICAL_LEFT_SQUARE_BRACKET = '\uFE47';
   char PRESENTATION_FORM_FOR_VERTICAL_RIGHT_SQUARE_BRACKET = '\uFE48';
   char SPACING_DASHED_OVERSCORE = '\uFE49';
   char SPACING_CENTERLINE_OVERSCORE = '\uFE4A';
   char SPACING_WAVY_OVERSCORE = '\uFE4B';
   char SPACING_DOUBLE_WAVY_OVERSCORE = '\uFE4C';
   char SPACING_DASHED_UNDERSCORE = '\uFE4D';
   char SPACING_CENTERLINE_UNDERSCORE = '\uFE4E';
   char SPACING_WAVY_UNDERSCORE = '\uFE4F';
}
