package unicode;
// Kugel's "Java Code & Tools Library", Copyright (c) 1999-2007, Theossos Comp Group

/**
 * Unicode CJK Symbols and Punctuation block with characters from u3000 to u303F.
 * @author Kugel, <i>Theossos Comp Group</i>
 * @version Unicode 4.1.0
 */
public interface CjkSymbolsAndPunctuation
{
   char IDEOGRAPHIC_SPACE = '\u3000';
   char IDEOGRAPHIC_COMMA = '\u3001';
   char IDEOGRAPHIC_PERIOD = '\u3002';
   char DITTO_MARK = '\u3003';
   char JAPANESE_INDUSTRIAL_STANDARD_SYMBOL = '\u3004';
   char IDEOGRAPHIC_ITERATION_MARK = '\u3005';
   char IDEOGRAPHIC_CLOSING_MARK = '\u3006';
   char IDEOGRAPHIC_NUMBER_ZERO = '\u3007';
   char OPENING_ANGLE_BRACKET = '\u3008';
   char CLOSING_ANGLE_BRACKET = '\u3009';
   char OPENING_DOUBLE_ANGLE_BRACKET = '\u300A';
   char CLOSING_DOUBLE_ANGLE_BRACKET = '\u300B';
   char OPENING_CORNER_BRACKET = '\u300C';
   char CLOSING_CORNER_BRACKET = '\u300D';
   char OPENING_WHITE_CORNER_BRACKET = '\u300E';
   char CLOSING_WHITE_CORNER_BRACKET = '\u300F';
   char OPENING_BLACK_LENTICULAR_BRACKET = '\u3010';
   char CLOSING_BLACK_LENTICULAR_BRACKET = '\u3011';
   char POSTAL_MARK = '\u3012';
   char GETA_MARK = '\u3013';
   char OPENING_TORTOISE_SHELL_BRACKET = '\u3014';
   char CLOSING_TORTOISE_SHELL_BRACKET = '\u3015';
   char OPENING_WHITE_LENTICULAR_BRACKET = '\u3016';
   char CLOSING_WHITE_LENTICULAR_BRACKET = '\u3017';
   char OPENING_WHITE_TORTOISE_SHELL_BRACKET = '\u3018';
   char CLOSING_WHITE_TORTOISE_SHELL_BRACKET = '\u3019';
   char OPENING_WHITE_SQUARE_BRACKET = '\u301A';
   char CLOSING_WHITE_SQUARE_BRACKET = '\u301B';
   char WAVE_DASH = '\u301C';
   char REVERSED_DOUBLE_PRIME_QUOTATION_MARK = '\u301D';
   char DOUBLE_PRIME_QUOTATION_MARK = '\u301E';
   char LOW_DOUBLE_PRIME_QUOTATION_MARK = '\u301F';
   char POSTAL_MARK_FACE = '\u3020';
   char HANGZHOU_NUMERAL_ONE = '\u3021';
   char HANGZHOU_NUMERAL_TWO = '\u3022';
   char HANGZHOU_NUMERAL_THREE = '\u3023';
   char HANGZHOU_NUMERAL_FOUR = '\u3024';
   char HANGZHOU_NUMERAL_FIVE = '\u3025';
   char HANGZHOU_NUMERAL_SIX = '\u3026';
   char HANGZHOU_NUMERAL_SEVEN = '\u3027';
   char HANGZHOU_NUMERAL_EIGHT = '\u3028';
   char HANGZHOU_NUMERAL_NINE = '\u3029';
   char IDEOGRAPHIC_LEVEL_TONE_MARK = '\u302A';
   char IDEOGRAPHIC_RISING_TONE_MARK = '\u302B';
   char IDEOGRAPHIC_DEPARTING_TONE_MARK = '\u302C';
   char IDEOGRAPHIC_ENTERING_TONE_MARK = '\u302D';
   char HANGUL_SINGLE_DOT_TONE_MARK = '\u302E';
   char HANGUL_DOUBLE_DOT_TONE_MARK = '\u302F';
   char WAVY_DASH = '\u3030';
   char VERTICAL_KANA_REPEAT_MARK = '\u3031';
   char VERTICAL_KANA_REPEAT_WITH_VOICED_SOUND_MARK = '\u3032';
   char VERTICAL_KANA_REPEAT_MARK_UPPER_HALF = '\u3033';
   char VERTICAL_KANA_REPEAT_WITH_VOICED_SOUND_MARK_UPPER_HALF = '\u3034';
   char VERTICAL_KANA_REPEAT_MARK_LOWER_HALF = '\u3035';
   char CIRCLED_POSTAL_MARK = '\u3036';
   char IDEOGRAPHIC_TELEGRAPH_LINE_FEED_SEPARATOR_SYMBOL = '\u3037';
   char HANGZHOU_NUMERAL_TEN = '\u3038';
   char HANGZHOU_NUMERAL_TWENTY = '\u3039';
   char HANGZHOU_NUMERAL_THIRTY = '\u303A';
   char VERTICAL_IDEOGRAPHIC_ITERATION_MARK = '\u303B';
   char MASU_MARK = '\u303C';
   char PART_ALTERNATION_MARK = '\u303D';
   char IDEOGRAPHIC_VARIATION_INDICATOR = '\u303E';
   char IDEOGRAPHIC_HALF_FILL_SPACE = '\u303F';
}
